// Author: Geoff Yoerger
// Date: Apr 17, 2014
// Assignment: Activity/Program PROG81.cpp
// Purpose: Generate voltrogs

#include "stdio.h"
#include <iostream>
using namespace std;
/**
 * Generate voltrogs
 * @param voltrog The voltrog the generate the new voltrog from
 * @return The new voltrog
 */
int genVoltrog(int voltrog) {
	// If it is odd
	if(voltrog % 2) {
		return ((3 * voltrog) + 1);
	} else { // If not then its even
		return (voltrog / 2);
	}
}
void printVoltrog(int numVs, int printThisVoltrog) {
	if(numVs % 6) { // See if its not the 6th voltrog
		cout << printThisVoltrog << " ";
	} else {
		cout << printThisVoltrog << "\n";
	}
}
void printResults(int initialV, int numVs) {
	cout << "\nIs all the voltrogs generated by " << initialV << ".\n";
	cout << "There were a total of " << numVs << " Voltrogs generated." << "\n";
}
/**
 * 
 * @return If the program ended succesfully
 */
int main() {
	cout << "Please enter the initial voltrog:" << "\n";
	int initial;
	cin >> initial;
	int numVoltrogs = 1;
	int gendVoltrog = genVoltrog(initial);
	printVoltrog(numVoltrogs, gendVoltrog);
	do {
		gendVoltrog = genVoltrog(gendVoltrog);
		numVoltrogs++;
		printVoltrog(numVoltrogs, gendVoltrog);
	} while(gendVoltrog != 1);
	printResults(initial, numVoltrogs);
	return 0;
}
